name: payrent
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.10.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # flutter_web_auth_2: ^4.1.0
  # flutter_web_auth_2_platform_interface: ^4.1.0

  cupertino_icons: ^1.0.8

  # State Management
  flutter_riverpod: ^2.5.1

  # Backend Appwrite
  appwrite: ^20.3.1 

  # Deep linking (remplace uni_links)
  app_links: ^6.3.2

  # HTTP client
  http: ^1.2.1

  # Google Fonts
  google_fonts: ^6.3.3

  # Email services
  resend: ^1.0.0
  mailer: ^6.6.0

  # Security / Hashing
  crypto: ^3.0.2

  # App info
  package_info_plus: ^8.0.0

  # URLs
  url_launcher: ^6.2.6

  # Permissions
  permission_handler: ^11.3.1

  # File handling
  dio: ^5.4.3
  path_provider: ^2.1.3
  open_filex: ^4.5.1

  # Local storage
  shared_preferences: ^2.5.4

  # Image picker
  image_picker: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/payrent_blanc.png
    - assets/images/payrent_marron.png

  fonts:
    - family: MuseoModerno
      fonts:
        - asset: assets/fonts/MuseoModerno.ttf

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icones/app_icon.png"
