name: payrent
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.2+2

environment:
  sdk: ^3.5.1

dependencies:
  image_picker: ^1.0.7
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  
  # State Management
  flutter_riverpod: ^2.5.1
  
  # Appwrite SDK pour le backend
  appwrite: ^13.0.0
  
  # Deep Linking - pour gérer les liens d'invitation
  uni_links: ^0.5.1
  
  # HTTP client pour les appels API (EmailService)
  http: ^1.2.1
  
  # Police Google Fonts
  google_fonts: ^6.3.3
  
  # Service d'envoi d'email Resend (officiel)
  resend: ^1.0.0
  
  # Email SMTP (Gmail fallback)
  mailer: ^6.6.0
  
  # Hashing
  crypto: ^3.0.2
  
  # Package info pour la version de l'app
  package_info_plus: ^8.0.0
  
  # Ouvrir des URLs (pour télécharger l'APK)
  url_launcher: ^6.2.5
  
  # Permissions pour Android
  permission_handler: ^11.3.0
  
  # Téléchargement de fichiers
  dio: ^5.4.0
  
  # Chemin pour stocker les fichiers
  path_provider: ^2.1.2
  
  # Installer l'APK (Android)
  open_filex: ^4.5.0
  shared_preferences: ^2.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/payrent_blanc.png
    - assets/images/payrent_marron.png

  fonts:
    - family: MuseoModerno
      fonts:
        - asset: assets/fonts/MuseoModerno.ttf 
